/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function version(): string
export interface CreateWindowOptions {
  name: string
  width: number
  height: number
}
export class Window {
  constructor(options: CreateWindowOptions)
  setSize(width: number, height: number): void
  end(): void
  hide(): void
  show(): void
  setResizable(resizable: boolean): void
  flush(): void
  get width(): number
  get height(): number
  setTitle(title: string): void
  get title(): string
  get visible(): boolean
  center(): void
  setFullscreen(fullscreen: boolean): void
}
export class Application {
  constructor()
  get version(): string
  createWindow(options: CreateWindowOptions): Window
  run(): void
  loadSystemFonts(): void
  redraw(): void
  wait(): void
  quit(): void
  get fonts(): Array<string>
  setBackgroundColor(color: string): void
}
